arch:
  - amd64
  - ppc64le
language: python
env:
  - EXTRA_CFLAGS="-Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wno-sign-compare -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wno-redundant-decls -Wundef -fdiagnostics-show-option -Wconversion -Wshadow-compatible-local -Wno-deprecated -Wno-deprecated-declarations -Wno-float-equal" EXTRA_CXXFLAGS="-Wctor-dtor-privacy -Wold-style-cast -Woverloaded-virtual -Wsign-promo -Wstrict-null-sentinel"
  - _CC=clang _CXX=clang++ _CPP=clang-cpp PACKAGES=clangxx EXTRA_CFLAGS="-Werror -Weverything -Wno-padded -Wno-disabled-macro-expansion -Wno-float-equal" EXTRA_CXXFLAGS="-Wno-exit-time-destructors -Wno-undefined-func-template -Wno-global-constructors -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-zero-as-null-pointer-constant -Wno-deprecated-declarations -Wno-shadow-field-in-constructor"
services:
  - docker
install:
  - sudo apt update
  - sudo apt install -y libc6-dbg
  - if [ "$TRAVIS_ARCH" = "amd64" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n e-antic-build -c conda-forge python=$TRAVIS_PYTHON_VERSION antic libflint arb valgrind autoconf automake cxx-compiler c-compiler libtool boost-cpp benchmark $PACKAGES
  - conda activate e-antic-build
  - export CC=${_CC:-$CC}
  - export CXX=${_CXX:-$CXX}
  - export CPP=${_CPP:-$CPP}
script:
  - set -e
  - ./bootstrap.sh
  - ./configure --prefix=$CONDA_PREFIX --enable-valgrind ${CONFIGURE} || (cat config.log; false)
  - make CFLAGS="$CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$CXXFLAGS $EXTRA_CFLAGS $EXTRA_CXXFLAGS"
  - ldd .libs/libeantic.so
  - make check CFLAGS="$CFLAGS $EXTRA_CFLAGS" CXXFLAGS="$CXXFLAGS $EXTRA_CFLAGS $EXTRA_CXXFLAGS" || (cat `find test-suite.log` /dev/null; false)
  - make check-valgrind || (cat `find test-suite-memcheck.log` /dev/null; false)
  - make distcheck
